# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main

pool:
  vmImage: "windows-latest"

stages:
  - stage: Test
    displayName: Test
    jobs:
      - deployment: Deploy
        displayName: Deploy Databricks Notebook
        environment: TEST
        variables:          
          - group: Test
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self              
              - task: databricksDeployScripts@0
                displayName: 'Deploy Databricks notebooks'
                inputs:
                  authMethod: 'servicePrincipal'
                  applicationId: '$(DevOps.ServicePrincipal.AppId)'
                  spSecret: '$(DevOps.ServicePrincipal.Secret)'
                  resourceGroup: '$(ResourceGroup.Name)'
                  workspace: '$(Databricks.Name)'
                  subscriptionId: '$(Subscription.Id)'
                  tenantId: '$(Tenant.Id)'
                  region: '$(ResourceGroup.Location)'
                  localPath: 'notebooks'
                  databricksPath: '/Shared'